import json

data = """{
  "code":200,
  "log_id":"7f90595db664519e",
  "msg":null,
  "data":{
    "_type":"SearchResponse",
    "queryContext":{
      "originalQuery":"2024年阿里巴巴的esg报告"
    },
    "webPages":{
      "webSearchUrl":"",
      "totalEstimatedMatches":8761784,
      "value":[
        {
          "id":null,
          "name":"阿里巴巴发布2024年ESG报告，阿里云数据中心清洁能源占比达56.0%",
          "url":"https://m.toutiao.com/article/7394409213570581004/",
          "displayUrl":"https://m.toutiao.com/article/7394409213570581004/",
          "snippet":"7月22日，阿里巴巴集团发布《环境、社会和治理报告（2024）》（以下简称“ESG报告”）提及，阿里巴巴自身运营减少碳排放量达232.0万吨，相比上一财年显著提升63.5%，其中，阿里云自建数据中心电力使用效率（PUE）从 2023财年1.215降至1.200，持续保持亚洲领先水平，清洁电力的使用比例已达到56%，领跑行业。作为全球领先的云计算服务提供商，阿里云一直努力构建一朵绿色低碳的云，并坚持将可持续发展的理念融入到业务设计中，为用户提供更高效且排放更低的云服务。根据Carbon Trust（碳信托）2022 年的《阿里云碳效能报告》，从本地化部署机房和服务器的传统模式切换到阿里云国内的客户，可避免85.5%的排放，最大的节约来自更优的能源使用效率（PUE）和更少的耗电量。同时，阿里云数据中心的精细化管理模式及智能运维平台遍布全球，不断以技术提效的方式降低PUE值，当PUE不断接近1，意味着能源基本都用于核心IT设备，效率越高。除此之外，创新技术也带来更高的能源利用效率。2024财年，阿里云数据中心在河北省张北县落地余热对市政供热项目，这让数据中心变成一个既提供云服务、又能供热的基...",
          "dateLastCrawled":"2024-07-22T18:45:00Z",
          "cachedPageUrl":null,
          "language":null,
          "isFamilyFriendly":null,
          "isNavigational":null
        },
        {
          "id":null,
          "name":"阿里巴巴发布2024年ESG报告: 保持前瞻、保持善意、保持务实",
          "url":"https://mparticle.uc.cn/article_org.html?uc_param_str=frdnsnpfvecpntnwprdssskt#!wm_cid=632492734097135616!!wm_id=44e0928349a54f2a93d29817b3d3721e",
          "displayUrl":"https://mparticle.uc.cn/article_org.html?uc_param_str=frdnsnpfvecpntnwprdssskt#!wm_cid=632492734097135616!!wm_id=44e0928349a54f2a93d29817b3d3721e",
          "snippet":"本报讯（记者袁传玺）7月22日，阿里巴巴集团发布《2024环境、社会和治理报告》（以下简称“ESG报告”）。在ESG战略方向的指引下，阿里巴巴进一步深化ESG治理，成效显著。报告指出，ESG的核心是围绕如何成为一家更好的公司。过去一年，阿里巴巴集团自身运营净碳排放和价值链碳强度继续实现“双降”，平台生态减排实现显著提升；将科技创新力量以及平台能力服务��无障碍、医疗、乡村、适老化等领域，并取得了不错的进展，医疗AI胰腺癌早筛项目落地、高德轮椅导航持续扩城、乡村特派员深入更多县域助力乡村建设；并深化了公司ESG治理架构。（企业供图） 2022财年，ESG正式确立为阿里巴巴的基石战略之一，并将长期战略方向体现在“阿里巴巴ESG七瓣花”中。它们和联合国的17个可持续发展目标高度相关，并充分考虑了发展中要解决的实际社会议题。2024财年是阿里巴巴深化ESG治理的一年。在环境保护议题中，阿里巴巴以ESG治理机制的保障为基础，继续探索“在发展中减碳”，通过科技提升能源利用效率，使用可再生能源、带动生态伙伴参与等方式，推进绿色低碳高质量发展。数据显示，2024财年，阿里巴巴实现自身运营碳排放和价值链...",
          "dateLastCrawled":"2024-07-22T16:10:00Z",
          "cachedPageUrl":null,
          "language":null,
          "isFamilyFriendly":null,
          "isNavigational":null
        },
        {
          "id":null,
          "name":"阿里巴巴2024年ESG报告来了！",
          "url":"https://m.163.com/dy/article/J7N5UA4F0517N211.html",
          "displayUrl":"https://m.163.com/dy/article/J7N5UA4F0517N211.html",
          "snippet":"0 今日，阿里巴巴对外发布2024年环境、社会和治理（ESG）报告。（注：报告186页臭长臭长的，作为一个职场自媒体，就给大家提炼一点我们职场人关注的） 查看精彩图片 关于员工发展： 据年报显示，其秉承“让员工成为更好的自己”的核心人才理念，正积极构建一个支持员工与企业共同成长的全方位生态系统。查看精彩图片 截至2024年3月31日，女性员工占比已达到47.2%，其中41.4%的管理人员为女性，高级管理人员中女性比例达到了30.0%。为进一步推动这一进程，阿里巴巴成立了“DEI专项组”，一方面在董事会可持续发展委员会的指导下，负责制定并推动多元化、平等与包容（DEI）政策的落地实施。另一方面，建立女性 STEM KOL 小组（技术女性意见领袖小组）展现女性榜样力量。除此之外，阿里更新全面风险管理体系类目树，将性骚扰、欺凌等风险事件纳入全面风险管理体系。2024财年，为吸引并保留顶尖人才，阿里巴巴不断优化薪酬福利体系。自2024年4月起，公司对股权激励政策进行了调整，将长期激励调整为“股权+长期现金”或“股票增值权/期权+长期现金”的组合方式，并部分调整为按季度归属。同时，阿里还为员工提...",
          "dateLastCrawled":"2024-07-22T14:28:00Z",
          "cachedPageUrl":null,
          "language":null,
          "isFamilyFriendly":null,
          "isNavigational":null
        },
        {
          "id":null,
          "name":"阿里巴巴ESG报告发布：揭秘融入业务背后的治理升级",
          "url":"https://baijiahao.baidu.com/s?id=1805979073005135624",
          "displayUrl":"https://baijiahao.baidu.com/s?id=1805979073005135624",
          "snippet":"阿里巴巴集团近日发布《2024环境、社会和治理报告》（以下简称“ESG报告”），围绕ESG这一全球关注的话题，在ESG战略方向的指引下，阿里巴巴正进一步深化ESG治理。报告指出，ESG的核心是围绕如何成为一家更好的公司。阿里巴巴ESG运营负责人许兰兰向金融界阐述了这家互联网巨头在ESG领域的探索与实践。ESG融入业务：不止于口号，更是实实在在的行动 ESG绝不能流于形式，而应该切实融入到公司的业务中去。许兰兰分享了她的切身感受。她坦言，在持续不断的宣导和培训中，业务部门意识到ESG不是额外的工作，而是业务不可或缺的一部分。我们希望每一位阿里人都能成为ESG的践行者，将ESG理念贯穿到日常工作中。事实上，阿里巴巴在2022财年提出了ESG工作的三大支柱：融入商业发展、科技创新和推动参与者生态。一年多来，这一理念已经落实到阿里巴巴各项业务中。例如，阿里云在数据中心的节能减排上不断探索，针对清洁能源和电力在过去几年里做了大量投入，特别是在WUE（水使用效率）和PUE（电力使用效率）平衡方面取得了显著成果。治理架构升级：ESG成为公司决策的重要考量 要让ESG真正落地，仅有口号远远不够，还需要...",
          "dateLastCrawled":"2024-07-30T12:56:00Z",
          "cachedPageUrl":null,
          "language":null,
          "isFamilyFriendly":null,
          "isNavigational":null
        },
        {
          "id":null,
          "name":"阿里巴巴发布 2024 年 ESG 报告：自身运营减排量同比增长 63.5%",
          "url":"https://view.inews.qq.com/a/20240722A0510K00",
          "displayUrl":"https://view.inews.qq.com/a/20240722A0510K00",
          "snippet":"IT之家 7 月 22 日消息，阿里巴巴今日发布 2024 年 ESG（环境、社会和治理）报告。过去一年，阿里巴巴集团自身运营净排放（量）达到 444.9 万吨，同比下降 5.0%；清洁电力使用比例达 39.0%。阿里巴巴自身运营减排量 232.0 万吨，同比增长 63.5%；阿里云清洁电力使用比例达到 56.0%，菜鸟仓内重复再使用的旧纸箱个数 4755.8 万个。在支持员工发展方面，阿里巴巴女性员工占比为 47.2%，41.4%的管理人员为女性；过去一年安排员工父母免费体检超 7.6 万人次。阿里巴巴全球授权专利已超 2 万项；85%的淘宝天猫活跃商家是中小微商家；已有超 32 万个产业代工厂在 1688 开店；淘宝天猫平台已提供约 20 亿商品。阿里巴巴“少年云助学计划”累计捐建 162 间“云计算机教室”，服务约 16 万名师生；“小鹿灯”项目累计援助 1967 名重疾儿童；饿了么平台活跃的无���骑手达到 5786 位。IT之家注意到，阿里巴巴集团首席执行官吴泳铭在 ESG 报告中提出：“努力成为一家更好的公司，需要我们参与解决一些共性的命题以及自身发展面临的命题。我希望这个...",
          "dateLastCrawled":"2024-07-22T14:31:00Z",
          "cachedPageUrl":null,
          "language":null,
          "isFamilyFriendly":null,
          "isNavigational":null
        },
        {
          "id":null,
          "name":"阿里巴巴发布2024年ESG报告: 碳排放持续“双降” 清洁电力占比达39.0%",
          "url":"https://mparticle.uc.cn/article_org.html?uc_param_str=frdnsnpfvecpntnwprdssskt#!wm_cid=632469603395576832!!wm_id=ffc598a56162428ebd68fda907bc329f",
          "displayUrl":"https://mparticle.uc.cn/article_org.html?uc_param_str=frdnsnpfvecpntnwprdssskt#!wm_cid=632469603395576832!!wm_id=ffc598a56162428ebd68fda907bc329f",
          "snippet":"过去一年，阿里巴巴集团自身运营净碳排放和价值链碳强度继续实现“双降”，平台生态减排实现显著提升；将科技创新力量以及平台能力服务于无障碍、医疗、乡村、适老化等领域，并取得了不错的进展，医疗AI胰腺癌早筛项目落地、高德轮椅导航持续扩城、乡村特派员深入更多县域助力乡村建设；并深化了公司ESG治理架构。“努力成为一家更好的公司，需要我们参与解决一些共性的命题以及自身发展面临的命题。我希望这个过程中，每一个阿里人都能学会做难而正确的选择，保持前瞻、保持善意、保持务实。阿里巴巴集团CEO吴泳铭在ESG报告中提出。推进绿色低碳高质量发展 数据显示，2024财年，阿里巴巴实现自身运营碳排放和价值链碳排放强度的“双降”目标；自身运营中的减排量达到232.0万吨，相比上一财年显著提升63.5%；清洁电力使用比例达到39.0%。价值链排放强度下降到8.1吨每百万元营收，同比降低7.0%。具体到各业务板块，阿里云自建数据中心电力使用效率（PUE）继续保持亚洲领先水平；清洁电力使用比例达到56.0%。菜鸟打造“数智循环物流”，在订单、仓储、包装、运输等重要物流环节开展减排行动，自身运营和价值链共计减排45.8万...",
          "dateLastCrawled":"2024-07-22T13:24:28Z",
          "cachedPageUrl":null,
          "language":null,
          "isFamilyFriendly":null,
          "isNavigational":null
        },
        {
          "id":null,
          "name":"阿里巴巴发布2024年ESG报告：碳排放持续“双降” ，清洁电力占比达39.0%",
          "url":"https://finance.sina.cn/2024-07-22/detail-incezcxu2012711.d.html",
          "displayUrl":"https://finance.sina.cn/2024-07-22/detail-incezcxu2012711.d.html",
          "snippet":"7月22日消息，阿里巴巴集团发布《2024环境、社会和治理报告》。“努力成为一家更好的公司，需要我们参与解决一些共性的命题以及自身发展面临的命题。",
          "dateLastCrawled":"2024-07-23T17:40:23Z",
          "cachedPageUrl":null,
          "language":null,
          "isFamilyFriendly":null,
          "isNavigational":null
        },
        {
          "id":null,
          "name":"阿里巴巴发布 2024 年 ESG 报告：自身运营减排量同比增长 63.5%",
          "url":"https://finance.sina.cn/2024-07-22/detail-inceyxsc1314529.d.html",
          "displayUrl":"https://finance.sina.cn/2024-07-22/detail-inceyxsc1314529.d.html",
          "snippet":"IT之家 7 月 22 日消息，阿里巴巴今日发布 2024 年 ESG（环境、社会和治理）报告。过去一年，阿里巴巴集团自身运营净排放（量）达到 444.9 万吨，同比下降 5.0%；清洁电力使用比例达 39.0%。阿里巴巴自身运营减排量 232.0 万吨，同比增长 63.5%；阿里云清洁电力使用比例达到 56.0%，菜鸟仓内重复再使用的旧纸箱个数 4755.8 万个。在支持员工发展方面，阿里巴巴女性员工占比为 47.2%，41.4%的管理人员为女性；过去一年安排员工父母免费体检超 7.6 万人次。阿里巴巴全球授权专利已超 2 万项；85%的淘宝天猫活跃商家是中小微商家；已有超 32 万个产业代工厂在 1688 开店；淘宝天猫平台已提供约 20 亿商品。阿里巴巴“少年云助学计划”累计捐建 162 间“云计算机教室”，服务约 16 万名师生；“小鹿灯”项目累计援助 1967 名重疾儿童；饿了么平台活跃的无声骑手达到 5786 位。IT之家注意到，阿里巴巴集团首席执行官吴泳铭在 ESG 报告中提出：“努力成为一家更好的公司，需要我们参与解决一些共性的命题以及自身发展面临的命题。我希望这个过程...",
          "dateLastCrawled":"2024-07-22T14:49:57Z",
          "cachedPageUrl":null,
          "language":null,
          "isFamilyFriendly":null,
          "isNavigational":null
        }
      ],
      "someResultsRemoved":true
    },
    "images":{
      "id":null,
      "readLink":null,
      "webSearchUrl":null,
      "value":[
        {
          "webSearchUrl":null,
          "name":null,
          "thumbnailUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyLzAwOTYwMjkxOGU0ZWVkMzhlNTkwNjk4YTcxZmYzNTRiLmpwZw==&sign=yx:BYUWV3ESju22qgiQsD-TuLhzfrc=&tv=240_320",
          "datePublished":null,
          "contentUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyLzAwOTYwMjkxOGU0ZWVkMzhlNTkwNjk4YTcxZmYzNTRiLmpwZw==&sign=yx:BYUWV3ESju22qgiQsD-TuLhzfrc=&tv=240_320",
          "hostPageUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyLzAwOTYwMjkxOGU0ZWVkMzhlNTkwNjk4YTcxZmYzNTRiLmpwZw==&sign=yx:BYUWV3ESju22qgiQsD-TuLhzfrc=&tv=240_320",
          "contentSize":null,
          "encodingFormat":null,
          "hostPageDisplayUrl":null,
          "width":552,
          "height":310,
          "thumbnail":null
        },
        {
          "webSearchUrl":null,
          "name":null,
          "thumbnailUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9pbmV3cy5ndGltZy5jb20vb21fYnQvT09nZ2ZYMXJWYTJYaGRkZmFYQlhBUFZUbmU3eUNfVXpmUVAxSHJpb243RjFZQUEvMTAwMA==&sign=yx:E4x74iJ-FEO4mheH54lNzlelXrk=&tv=240_320",
          "datePublished":null,
          "contentUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9pbmV3cy5ndGltZy5jb20vb21fYnQvT09nZ2ZYMXJWYTJYaGRkZmFYQlhBUFZUbmU3eUNfVXpmUVAxSHJpb243RjFZQUEvMTAwMA==&sign=yx:E4x74iJ-FEO4mheH54lNzlelXrk=&tv=240_320",
          "hostPageUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9pbmV3cy5ndGltZy5jb20vb21fYnQvT09nZ2ZYMXJWYTJYaGRkZmFYQlhBUFZUbmU3eUNfVXpmUVAxSHJpb243RjFZQUEvMTAwMA==&sign=yx:E4x74iJ-FEO4mheH54lNzlelXrk=&tv=240_320",
          "contentSize":null,
          "encodingFormat":null,
          "hostPageDisplayUrl":null,
          "width":1000,
          "height":1333,
          "thumbnail":null
        },
        {
          "webSearchUrl":null,
          "name":null,
          "thumbnailUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9pbmV3cy5ndGltZy5jb20vb21fYnQvT3dteGRpNlBLRFFOemR2RUV6MWxYdVdLMmIwNjloZzRXbGE1eEJCbDA4TC13QUEvNjQx&sign=yx:kVCUFe8GyltszMeij9hE3N7KyYs=&tv=240_320",
          "datePublished":null,
          "contentUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9pbmV3cy5ndGltZy5jb20vb21fYnQvT3dteGRpNlBLRFFOemR2RUV6MWxYdVdLMmIwNjloZzRXbGE1eEJCbDA4TC13QUEvNjQx&sign=yx:kVCUFe8GyltszMeij9hE3N7KyYs=&tv=240_320",
          "hostPageUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9pbmV3cy5ndGltZy5jb20vb21fYnQvT3dteGRpNlBLRFFOemR2RUV6MWxYdVdLMmIwNjloZzRXbGE1eEJCbDA4TC13QUEvNjQx&sign=yx:kVCUFe8GyltszMeij9hE3N7KyYs=&tv=240_320",
          "contentSize":null,
          "encodingFormat":null,
          "hostPageDisplayUrl":null,
          "width":960,
          "height":1280,
          "thumbnail":null
        },
        {
          "webSearchUrl":null,
          "name":null,
          "thumbnailUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyL2MzODJmMDk4NjkyODMwZjVhNDZlMmQ1MjdlNTkzM2JhLmpwZw==&sign=yx:NL3OE9i9sRs7CS-i6yA5Sg3jMys=&tv=240_320",
          "datePublished":null,
          "contentUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyL2MzODJmMDk4NjkyODMwZjVhNDZlMmQ1MjdlNTkzM2JhLmpwZw==&sign=yx:NL3OE9i9sRs7CS-i6yA5Sg3jMys=&tv=240_320",
          "hostPageUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyL2MzODJmMDk4NjkyODMwZjVhNDZlMmQ1MjdlNTkzM2JhLmpwZw==&sign=yx:NL3OE9i9sRs7CS-i6yA5Sg3jMys=&tv=240_320",
          "contentSize":null,
          "encodingFormat":null,
          "hostPageDisplayUrl":null,
          "width":1080,
          "height":606,
          "thumbnail":null
        },
        {
          "webSearchUrl":null,
          "name":null,
          "thumbnailUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyLzZjYzNmZGQ3Mjc1OWZiNmZlYTFiNDM3NzVjMmQ0OTY0LmpwZw==&sign=yx:8klz1ttyv9UhFM_254powH7bIhg=&tv=240_320",
          "datePublished":null,
          "contentUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyLzZjYzNmZGQ3Mjc1OWZiNmZlYTFiNDM3NzVjMmQ0OTY0LmpwZw==&sign=yx:8klz1ttyv9UhFM_254powH7bIhg=&tv=240_320",
          "hostPageUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyLzZjYzNmZGQ3Mjc1OWZiNmZlYTFiNDM3NzVjMmQ0OTY0LmpwZw==&sign=yx:8klz1ttyv9UhFM_254powH7bIhg=&tv=240_320",
          "contentSize":null,
          "encodingFormat":null,
          "hostPageDisplayUrl":null,
          "width":1080,
          "height":652,
          "thumbnail":null
        },
        {
          "webSearchUrl":null,
          "name":null,
          "thumbnailUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyL2YzNWE2Y2IxZTNlNThiMWMyMmEyZGQyOTI5YzI5ZWJmLmpwZw==&sign=yx:xVbjmLa9TGOAnzkL4t_FYQBwPmc=&tv=240_320",
          "datePublished":null,
          "contentUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyL2YzNWE2Y2IxZTNlNThiMWMyMmEyZGQyOTI5YzI5ZWJmLmpwZw==&sign=yx:xVbjmLa9TGOAnzkL4t_FYQBwPmc=&tv=240_320",
          "hostPageUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cDovL2RheXUtaW1nLnVjLmNuL2NvbHVtYnVzL2ltZy9vYy8xMDAyL2YzNWE2Y2IxZTNlNThiMWMyMmEyZGQyOTI5YzI5ZWJmLmpwZw==&sign=yx:xVbjmLa9TGOAnzkL4t_FYQBwPmc=&tv=240_320",
          "contentSize":null,
          "encodingFormat":null,
          "hostPageDisplayUrl":null,
          "width":1080,
          "height":607,
          "thumbnail":null
        },
        {
          "webSearchUrl":null,
          "name":null,
          "thumbnailUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9uLnNpbmFpbWcuY24vc3BpZGVyMjAyNDA3MjIvNjQvdzU1M2gzMTEvMjAyNDA3MjIvNWY0ZS1mNGNkYTEzNDJjNjM2NzQ5YjRjZmRlNTY4MjY2NjBmNS5qcGc=&sign=yx:c3y5GQLl99ZOlUsawBJEfkwVy0c=&tv=240_320",
          "datePublished":null,
          "contentUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9uLnNpbmFpbWcuY24vc3BpZGVyMjAyNDA3MjIvNjQvdzU1M2gzMTEvMjAyNDA3MjIvNWY0ZS1mNGNkYTEzNDJjNjM2NzQ5YjRjZmRlNTY4MjY2NjBmNS5qcGc=&sign=yx:c3y5GQLl99ZOlUsawBJEfkwVy0c=&tv=240_320",
          "hostPageUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9uLnNpbmFpbWcuY24vc3BpZGVyMjAyNDA3MjIvNjQvdzU1M2gzMTEvMjAyNDA3MjIvNWY0ZS1mNGNkYTEzNDJjNjM2NzQ5YjRjZmRlNTY4MjY2NjBmNS5qcGc=&sign=yx:c3y5GQLl99ZOlUsawBJEfkwVy0c=&tv=240_320",
          "contentSize":null,
          "encodingFormat":null,
          "hostPageDisplayUrl":null,
          "width":553,
          "height":311,
          "thumbnail":null
        },
        {
          "webSearchUrl":null,
          "name":null,
          "thumbnailUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9uLnNpbmFpbWcuY24vc3BpZGVyMjAyNDA3MjIvNzQwL3c2NjBoODgwLzIwMjQwNzIyLzNlZTMtZThhMzU0NDM0MjdhY2E5YTcwN2Q5M2ZhZDQ3OThiNWIuanBn&sign=yx:aVtmsQW2B17MEfNK_Xzehof1mZg=&tv=240_320",
          "datePublished":null,
          "contentUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9uLnNpbmFpbWcuY24vc3BpZGVyMjAyNDA3MjIvNzQwL3c2NjBoODgwLzIwMjQwNzIyLzNlZTMtZThhMzU0NDM0MjdhY2E5YTcwN2Q5M2ZhZDQ3OThiNWIuanBn&sign=yx:aVtmsQW2B17MEfNK_Xzehof1mZg=&tv=240_320",
          "hostPageUrl":"http://s2.zimgs.cn/ims?kt=url&at=smstruct&key=aHR0cHM6Ly9uLnNpbmFpbWcuY24vc3BpZGVyMjAyNDA3MjIvNzQwL3c2NjBoODgwLzIwMjQwNzIyLzNlZTMtZThhMzU0NDM0MjdhY2E5YTcwN2Q5M2ZhZDQ3OThiNWIuanBn&sign=yx:aVtmsQW2B17MEfNK_Xzehof1mZg=&tv=240_320",
          "contentSize":null,
          "encodingFormat":null,
          "hostPageDisplayUrl":null,
          "width":660,
          "height":880,
          "thumbnail":null
        }
      ],
      "isFamilyFriendly":null
    },
    "videos":{
      "id":null,
      "readLink":null,
      "webSearchUrl":null,
      "isFamilyFriendly":null,
      "scenario":null,
      "value":[ ]
    }
  }
}"""


def parse(data):
    json_data = json.loads(data)
    results = json_data["data"]["webPages"]["value"]
    for r in results:
        print(r["name"])
        print(r["url"])
        print(r["snippet"])

parse(data)